DROP SEQUENCE SPONSOR_ID_SEQ;
DROP SEQUENCE SPORT_OBJECT_ID_SEQ;
DROP SEQUENCE MATCH_ID_SEQ;
DROP SEQUENCE PLAYER_ID_SEQ;
DROP SEQUENCE TEAM_ID_SEQ;
DROP SEQUENCE STATS_ID_SEQ;

CREATE SEQUENCE MATCH_ID_SEQ INCREMENT BY 1 START WITH 0 NOCACHE MINVALUE 0;
CREATE SEQUENCE PLAYER_ID_SEQ INCREMENT BY 1 START WITH 0 NOCACHE MINVALUE 0;
CREATE SEQUENCE TEAM_ID_SEQ INCREMENT BY 1 START WITH 0 NOCACHE MINVALUE 0;
CREATE SEQUENCE SPONSOR_ID_SEQ INCREMENT BY 1 START WITH 0 NOCACHE MINVALUE 0;
CREATE SEQUENCE SPORT_OBJECT_ID_SEQ INCREMENT BY 1 START WITH 0 NOCACHE MINVALUE 0;
CREATE SEQUENCE STATS_ID_SEQ INCREMENT BY 1 START WITH 0 NOCACHE MINVALUE 0;

DELETE FROM TEAM;
DELETE FROM PLAYER;
DELETE FROM PLAYERSTATS;
DELETE FROM MATCH;
DELETE FROM SPORTOBJECT;
DELETE FROM SPONSOR;

--DODAWANIE DRU¯YN;
BEGIN
    TEAM_PACKAGE.ADD_TEAM('BOSTON CELTICS');
    TEAM_PACKAGE.ADD_TEAM('BROOKLYN NETS');
    TEAM_PACKAGE.ADD_TEAM('NEW YORK KNICKS');
    TEAM_PACKAGE.ADD_TEAM('PHILADELPHIA 76ERS');
    TEAM_PACKAGE.ADD_TEAM('TORONTO RAPTORS');
END;
/
--DODAWANIE ZAWODNIKOW
BEGIN
    --CELTICS
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-09-1999', 'MM-DD-YYYY'), 'DREW', 'PETERSON', 'F', 0);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('12-03-1987', 'MM-DD-YYYY'), 'Jayson', 'Tatum', 'F-G', 0);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-05-1976', 'MM-DD-YYYY'), 'Jrue', 'Holiday', 'G', 0);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-01-1989', 'MM-DD-YYYY'), 'Jaylen', 'Brown', 'G-F', 0);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-10-1990', 'MM-DD-YYYY'), 'Kristaps', 'Porzingis', 'F-C', 0);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-03-1991', 'MM-DD-YYYY'), 'Derrick', 'White', 'G', 0);
    
    --BROOKLYN
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-12-1984', 'MM-DD-YYYY'), 'Dariq', 'Whitehead', 'F', 1);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-04-1993', 'MM-DD-YYYY'), 'Royce', 'O''Neale', 'F-G', 1);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-02-1992', 'MM-DD-YYYY'), 'Mikal', 'Bridges', 'G', 1);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-02-1990', 'MM-DD-YYYY'), 'Cameron', 'Johnson', 'G-F', 1);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-10-1992', 'MM-DD-YYYY'), 'Lonnie', 'Walker IV.', 'F-C', 1);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-09-1993', 'MM-DD-YYYY'), 'Trendon', 'Watford', 'G', 1);
    
    --KNICKS
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-06-1989', 'MM-DD-YYYY'), 'Donte', 'DiVincenzo', 'F', 2);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-06-1990', 'MM-DD-YYYY'), 'Jacob', 'Toppin', 'F-G', 2);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-08-1993', 'MM-DD-YYYY'), 'Miles', 'McBride', 'G', 2);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-03-1995', 'MM-DD-YYYY'), 'Josh', 'Hart', 'G-F', 2);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('04-09-1997', 'MM-DD-YYYY'), 'Malachi', 'Flynn IV.', 'F-C', 2);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('08-02-1990', 'MM-DD-YYYY'), 'Precious', 'Achiuwa', 'G', 2);
    
    --76ers
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('12-03-1997', 'MM-DD-YYYY'), 'Tyrese', 'Maxey', 'F', 3);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-05-1994', 'MM-DD-YYYY'), 'KJ', 'Martin', 'F-G', 3);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-07-1993', 'MM-DD-YYYY'), 'Mo', 'Bamba', 'G', 3);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('10-07-1995', 'MM-DD-YYYY'), 'Tobias', 'Harris', 'G-F', 3);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-08-1992', 'MM-DD-YYYY'), 'Jaden', 'Springer', 'F-C', 3);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-10-1991', 'MM-DD-YYYY'), 'Ricky', 'Council IV', 'G', 3);
    
    --RAPTORS
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('10-10-1990', 'MM-DD-YYYY'), 'Javon', 'Freeman-Liberty', 'F', 4);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-04-1987', 'MM-DD-YYYY'), 'Gradey', 'Dick', 'F-G', 4);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-02-1996', 'MM-DD-YYYY'), 'Jalen', 'McDaniels', 'G', 4);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-09-1994', 'MM-DD-YYYY'), 'Scottie', 'Barnes', 'G-F', 4);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-01-1984', 'MM-DD-YYYY'), 'Immanuel', 'Quickley', 'F-C', 4);
    PLAYER_PACKAGE.ADD_PLAYER(TO_DATE('11-03-1992', 'MM-DD-YYYY'), 'RJ', 'Barrett IV', 'G', 4);
END;
/
--OBIEKTY SPORTOWE
BEGIN
    TEAM_PACKAGE.ADD_SPORT_OBJECT('TD Garden', 0);
    TEAM_PACKAGE.ADD_SPORT_OBJECT('Barclays Center', 1);
    TEAM_PACKAGE.ADD_SPORT_OBJECT('Madison Square Garden', 2);
    TEAM_PACKAGE.ADD_SPORT_OBJECT('Wells Fargo Center', 3);
    TEAM_PACKAGE.ADD_SPORT_OBJECT('Scotiabank Arena', 4);
END;
--SPONSORZY
/
BEGIN
    TEAM_PACKAGE.CREATE_SPONSOR('MOTOROLA', 150000);
    TEAM_PACKAGE.CREATE_SPONSOR('DISNEY', 360000);
    TEAM_PACKAGE.CREATE_SPONSOR('PAYPAL', 230000);
    TEAM_PACKAGE.CREATE_SPONSOR('TESLA', 400000);
    TEAM_PACKAGE.CREATE_SPONSOR('COCA COLA', 500000);
    TEAM_PACKAGE.CREATE_SPONSOR('RAKUTEN', 450000);
    TEAM_PACKAGE.CREATE_SPONSOR('CHIME', 130000);
    TEAM_PACKAGE.CREATE_SPONSOR('FEASTABLES', 160000);
    TEAM_PACKAGE.CREATE_SPONSOR('WEBULL', 50000);
    TEAM_PACKAGE.CREATE_SPONSOR('VISTAPRINT', 250000);
    TEAM_PACKAGE.CREATE_SPONSOR('NIKE', 200000);
    TEAM_PACKAGE.CREATE_SPONSOR('ADDIDAS', 265000);
    TEAM_PACKAGE.CREATE_SPONSOR('PUMA', 300000);
    TEAM_PACKAGE.CREATE_SPONSOR( 'GOOGLE', 420000);
    
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(1,0);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(2,1);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(3,1);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(4,1);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(5,2);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(6,2);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(7,3);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(8,4);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(9,4);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(10,1);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(11,3);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(12,2);
    TEAM_PACKAGE.ADD_SPONSOR_TO_THE_TEAM(13,0);
END;
/
BEGIN
    TEAM_PACKAGE.PRINT_SPONSORS_FROM_TEAM(1);
END;
/
BEGIN
    TEAM_PACKAGE.PRINT_PLAYERS_FROM_TEAM(1);
END;
/
BEGIN
    SCHEDULE_PACKAGE.generate_schedule(TO_DATE('13-02-2024', 'MM-DD-YYYY'));
END;
/
BEGIN
    MATCH_PACKAGE.update_score_with_match_id(31, 115, 110);
    PLAYER_STATS_PACKAGE.update_player_stats(0, 15, 10, 23, 13, 40, 12);
    MATCH_PACKAGE.display_team_ranking;
    PLAYER_STATS_PACKAGE.display_player_stats(1);
END;
/
BEGIN
    MATCH_PACKAGE.update_score_with_match_id(32, 115, 110);
END;
/
BEGIN
    PLAYER_STATS_PACKAGE.display_player_stats(13);
END;
/
BEGIN
    TEAM_PACKAGE.PRINT_PLAYERS_FROM_TEAM(0);
    PLAYER_PACKAGE.TRANSFER_PLAYER(1,4);
    TEAM_PACKAGE.PRINT_PLAYERS_FROM_TEAM(0);
    TEAM_PACKAGE.PRINT_PLAYERS_FROM_TEAM(4);
END;
/
BEGIN
    SCHEDULE_PACKAGE.PRINT_SCHEDULE;
END;
/
BEGIN
    SCHEDULE_PACKAGE.PRINT_MATCHES_FOR_TEAM(1);
END;
/
BEGIN
    PLAYER_STATS_PACKAGE.display_all_player_stats;
END;
/
BEGIN
    PLAYER_STATS_PACKAGE.display_all_player_stats_from_match(32);
END;
/
