  INSERT INTO MATCH (MATCH_ID, MATCH_DATE, SPORT_OBJECT_ID, TEAM_HOME_ID, TEAM_AWAY_ID, SCORE_HOME, SCORE_AWAY)
  VALUES(1,
  TO_DATE('24-10-2023 12:00:00', 'DD-MM-YYYY, HH24:MI:SS'),
  NULL,
  NULL, 
  NULL,
  0, 
  0);
  INSERT INTO MATCH (MATCH_ID, MATCH_DATE, SPORT_OBJECT_ID, TEAM_HOME_ID, TEAM_AWAY_ID, SCORE_HOME, SCORE_AWAY)
  VALUES(2,
  TO_DATE('24-10-2023 13:00:00', 'DD-MM-YYYY, HH24:MI:SS'),
  NULL,
  NULL, 
  NULL,
  0, 
  0);
  INSERT INTO MATCH (MATCH_ID, MATCH_DATE, SPORT_OBJECT_ID, TEAM_HOME_ID, TEAM_AWAY_ID, SCORE_HOME, SCORE_AWAY)
  VALUES(3,
  TO_DATE('24-10-2023 14:00:00', 'DD-MM-YYYY, HH24:MI:SS'),
  NULL,
  NULL, 
  NULL,
  0, 
  0);
  
BEGIN
  SCHEDULE_PACKAGE.GENERATE_SCHEDULE;
END;
/

SELECT MATCH_ID, TO_CHAR(MATCH_DATE, 'DD-MM-YY HH:MM:SS') FROM MATCH;

DELETE FROM Match;
DELETE FROM TEAM;
DELETE FROM SPORTOBJECT;

CREATE SEQUENCE MATCH_ID_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
DROP SEQUENCE MATCH_ID_SEQ;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY HH24:MI:SS';

        SELECT A.name AS team_a_name, B.name AS team_b_name
        FROM TEAM A
        CROSS JOIN TEAM B
        WHERE A.name != B.name
        ORDER BY DBMS_RANDOM.RANDOM;
    
    
SELECT MATCH_ID, MATCH_DATE, DEREF(M.SPORT_OBJECT_ID).OBJECT_NAME, DEREF(M.TEAM_HOME_ID).NAME, DEREF(M.TEAM_AWAY_ID).NAME, SCORE_HOME, SCORE_AWAY FROM MATCH M;    