--ZAWODNICY
DELETE FROM PLAYER;

CREATE SEQUENCE player_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;
  
--CELTICS

INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MM-DD-YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Drew' AS FIRST_NAME, 'Peterson' AS LAST_NAME, '11-09-1999' AS BIRTHDATE, 'F' AS POSITION FROM DUAL UNION ALL
  SELECT 'Jayson', 'Tatum', '03-03-1998', 'F-G' FROM DUAL UNION ALL
  SELECT 'Jrue', 'Holiday', '06-12-1990', 'G' FROM DUAL UNION ALL
  SELECT 'Jaylen', 'Brown', '10-24-1996', 'G-F' FROM DUAL UNION ALL
  SELECT 'Kristaps', 'Porzingis', '08-02-1995', 'F-C' FROM DUAL UNION ALL
  SELECT 'Derrick', 'White', '07-02-1994', 'G' FROM DUAL UNION ALL
  SELECT 'Payton', 'Pritchard', '01-28-1998', 'G' FROM DUAL UNION ALL
  SELECT 'Oshae', 'Brissett', '06-20-1998', 'F-G' FROM DUAL UNION ALL
  SELECT 'JD', 'Davison', '10-03-2002', 'G' FROM DUAL UNION ALL
  SELECT 'Jordan', 'Walsh', '03-03-2004', 'G' FROM DUAL UNION ALL
  SELECT 'Sam', 'Hauser', '12-08-1997', 'F' FROM DUAL UNION ALL
  SELECT 'Luke', 'Kornet', '07-15-1995', 'C-F' FROM DUAL UNION ALL
  SELECT 'Al', 'Horford', '06-03-1986', 'C-F' FROM DUAL UNION ALL
  SELECT 'Dalano', 'Banton', '11-07-1999', 'F' FROM DUAL UNION ALL
  SELECT 'Svi', 'Mykhailiuk', '06-10-1997', 'G-F' FROM DUAL
);

--Brooklyn Nets
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Dariq' AS FIRST_NAME, 'Whitehead' AS LAST_NAME, 'AUG 01, 2004' AS BIRTHDATE, 'F' AS POSITION FROM DUAL UNION ALL
  SELECT 'Royce', 'O''Neale', 'JUN 05, 1993', 'F' FROM DUAL UNION ALL
  SELECT 'Mikal', 'Bridges', 'AUG 30, 1996', 'G-F' FROM DUAL UNION ALL
  SELECT 'Cameron', 'Johnson', 'MAR 03, 1996', 'F' FROM DUAL UNION ALL
  SELECT 'Dennis', 'Smith Jr.', 'NOV 25, 1997', 'G' FROM DUAL UNION ALL
  SELECT 'Lonnie', 'Walker IV', 'DEC 14, 1998', 'G-F' FROM DUAL UNION ALL
  SELECT 'Trendon', 'Watford', 'NOV 09, 2000', 'F' FROM DUAL UNION ALL
  SELECT 'Ben', 'Simmons', 'JUL 20, 1996', 'G-F' FROM DUAL UNION ALL
  SELECT 'Harry', 'Giles III', 'APR 22, 1998', 'F-C' FROM DUAL UNION ALL
  SELECT 'Day''Ron', 'Sharpe', 'NOV 06, 2001', 'C' FROM DUAL UNION ALL
  SELECT 'Noah', 'Clowney', 'JUL 14, 2004', 'F' FROM DUAL UNION ALL
  SELECT 'Jalen', 'Wilson', 'NOV 04, 2000', 'F' FROM DUAL UNION ALL
  SELECT 'Cam', 'Thomas', 'OCT 13, 2001', 'G' FROM DUAL UNION ALL
  SELECT 'Spencer', 'Dinwiddie', 'APR 06, 1993', 'G' FROM DUAL UNION ALL
  SELECT 'Dorian', 'Finney-Smith', 'MAY 04, 1993', 'F' FROM DUAL UNION ALL
  SELECT 'Nic', 'Claxton', 'APR 17, 1999', 'C' FROM DUAL UNION ALL
  SELECT 'Keon', 'Johnson', 'MAR 10, 2002', 'G' FROM DUAL
);


--NEW YORK KNICKS
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Donte' AS FIRST_NAME, 'DiVincenzo' AS LAST_NAME, 'JAN 31, 1997' AS BIRTHDATE, 'G' AS POSITION FROM DUAL UNION ALL
  SELECT 'Jacob', 'Toppin', 'MAY 08, 2000', 'F' FROM DUAL UNION ALL
  SELECT 'Miles', 'McBride', 'SEP 08, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'Josh', 'Hart', 'MAR 06, 1995', 'G' FROM DUAL UNION ALL
  SELECT 'Malachi', 'Flynn', 'MAY 09, 1998', 'G' FROM DUAL UNION ALL
  SELECT 'Duane Washington Jr.', 'MAR 24, 2000', 'MAR 24, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'Precious', 'Achiuwa', 'SEP 19, 1999', 'F' FROM DUAL UNION ALL
  SELECT 'Quentin', 'Grimes', 'MAY 08, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'OG', 'Anunoby', 'JUL 17, 1997', 'F-G' FROM DUAL UNION ALL
  SELECT 'Jalen', 'Brunson', 'AUG 31, 1996', 'G' FROM DUAL UNION ALL
  SELECT 'Evan', 'Fournier', 'OCT 29, 1992', 'G-F' FROM DUAL UNION ALL
  SELECT 'Mitchell', 'Robinson', 'APR 01, 1998', 'C-F' FROM DUAL UNION ALL
  SELECT 'Julius', 'Randle', 'NOV 29, 1994', 'F-C' FROM DUAL UNION ALL
  SELECT 'Charlie Brown Jr.', 'FEB 02, 1997', 'FEB 02, 1997', 'G' FROM DUAL UNION ALL
  SELECT 'Jericho', 'Sims', 'OCT 20, 1998', 'C' FROM DUAL UNION ALL
  SELECT 'Ryan', 'Arcidiacono', 'MAR 26, 1994', 'G' FROM DUAL UNION ALL
  SELECT 'Isaiah', 'Hartenstein', 'MAY 05, 1998', 'C-F' FROM DUAL
);





--Bucks
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Damian', 'Lillard', 'JUL 15, 1990', 'G', NULL FROM DUAL UNION ALL
  SELECT 'MarJon', 'Beauchamp', 'OCT 12, 2000', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Malik', 'Beasley', 'NOV 26, 1996', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Chris', 'Livingston', 'OCT 15, 2003', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Bobby', 'Portis', 'FEB 10, 1995', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Brook', 'Lopez', 'APR 01, 1988', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Cameron', 'Payne', 'AUG 08, 1994', 'G', NULL FROM DUAL UNION ALL
  SELECT 'AJ', 'Green', 'SEP 27, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Khris', 'Middleton', 'AUG 12, 1991', 'F', NULL FROM DUAL UNION ALL
  SELECT 'TyTy', 'Washington Jr.', 'NOV 15, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Pat', 'Connaughton', 'JAN 06, 1993', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Giannis', 'Antetokounmpo', 'DEC 06, 1994', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Robin', 'Lopez', 'APR 01, 1988', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Thanasis', 'Antetokounmpo', 'JUL 18, 1992', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Andre', 'Jackson Jr.', 'NOV 13, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Jae', 'Crowder', 'JUL 06, 1990', 'F', NULL FROM DUAL
);


--76ERS
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Tyrese' AS FIRST_NAME, 'Maxey' AS LAST_NAME, 'NOV 04, 2000' AS BIRTHDATE, 'G' AS POSITION FROM DUAL UNION ALL
  SELECT 'KJ', 'Martin', 'JAN 06, 2001', 'F' FROM DUAL UNION ALL
  SELECT 'Marcus Morris Sr.', 'SEP 02, 1989', 'SEP 02, 1989', 'F' FROM DUAL UNION ALL
  SELECT 'Mo', 'Bamba', 'MAY 12, 1998', 'C' FROM DUAL UNION ALL
  SELECT 'De''Anthony', 'Melton', 'MAY 28, 1998', 'G' FROM DUAL UNION ALL
  SELECT 'Kelly', 'Oubre Jr.', 'DEC 09, 1995', 'F-G' FROM DUAL UNION ALL
  SELECT 'Jaden', 'Springer', 'SEP 25, 2002', 'G' FROM DUAL UNION ALL
  SELECT 'Tobias', 'Harris', 'JUL 15, 1992', 'F' FROM DUAL UNION ALL
  SELECT 'Ricky', 'Council IV', 'AUG 03, 2001', 'G' FROM DUAL UNION ALL
  SELECT 'Joel', 'Embiid', 'MAR 16, 1994', 'C-F' FROM DUAL UNION ALL
  SELECT 'Patrick', 'Beverley', 'JUL 12, 1988', 'G' FROM DUAL UNION ALL
  SELECT 'Terquavion', 'Smith', 'DEC 31, 2002', 'G' FROM DUAL UNION ALL
  SELECT 'Danuel', 'House Jr.', 'JUN 07, 1993', 'F-G' FROM DUAL UNION ALL
  SELECT 'Furkan', 'Korkmaz', 'JUL 24, 1997', 'G-F' FROM DUAL UNION ALL
  SELECT 'Robert', 'Covington', 'DEC 14, 1990', 'F' FROM DUAL UNION ALL
  SELECT 'Kenneth', 'Lofton Jr.', 'AUG 14, 2002', 'F' FROM DUAL UNION ALL
  SELECT 'Nicolas', 'Batum', 'DEC 14, 1988', 'G-F' FROM DUAL UNION ALL
  SELECT 'Paul', 'Reed', 'JUN 14, 1999', 'F' FROM DUAL
);


--Raptors

INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Javon', 'Freeman-Liberty', 'OCT 20, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Gradey', 'Dick', 'NOV 20, 2003', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Jalen', 'McDaniels', 'JAN 31, 1998', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Scottie', 'Barnes', 'AUG 01, 2001', 'F-G', NULL FROM DUAL UNION ALL
  SELECT 'Immanuel', 'Quickley', 'JUN 17, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'RJ', 'Barrett', 'JUN 14, 2000', 'F-G', NULL FROM DUAL UNION ALL
  SELECT 'Jontay', 'Porter', 'NOV 15, 1999', 'C-F', NULL FROM DUAL UNION ALL
  SELECT 'Garrett', 'Temple', 'MAY 08, 1986', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Dennis', 'Schroder', 'SEP 15, 1993', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Jakob', 'Poeltl', 'OCT 15, 1995', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Thaddeus', 'Young', 'JUN 21, 1988', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Markquis', 'Nowell', 'DEC 25, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Chris', 'Boucher', 'JAN 11, 1993', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Otto', 'Porter Jr.', 'JUN 03, 1993', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Gary', 'Trent Jr.', 'JAN 18, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Christian', 'Koloko', 'JUN 20, 2000', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Pascal', 'Siakam', 'APR 02, 1994', 'F', NULL FROM DUAL
);


--Bulls
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Henri', 'Drell', 'APR 25, 2000', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Coby', 'White', 'FEB 16, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Lonzo', 'Ball', 'OCT 27, 1997', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Andre', 'Drummond', 'AUG 10, 1993', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Jevon', 'Carter', 'SEP 14, 1995', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Alex', 'Caruso', 'FEB 28, 1994', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Zach', 'LaVine', 'MAR 10, 1995', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Nikola', 'Vucevic', 'OCT 24, 1990', 'C', NULL FROM DUAL UNION ALL
  SELECT 'DeMar', 'DeRozan', 'AUG 07, 1989', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Ayo', 'Dosunmu', 'JAN 17, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Torrey', 'Craig', 'DEC 19, 1990', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Julian', 'Phillips', 'NOV 05, 2003', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Onuralp', 'Bitim', 'MAR 31, 1999', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Adama', 'Sanogo', 'FEB 12, 2002', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Dalen', 'Terry', 'JUL 12, 2002', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Terry', 'Taylor', 'SEP 23, 1999', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Patrick', 'Williams', 'AUG 26, 2001', 'F', NULL FROM DUAL
);


--Cleveland cavaliers
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Max', 'Strus', 'MAR 28, 1996', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Ty', 'Jerome', 'JUL 08, 1997', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Caris', 'LeVert', 'AUG 25, 1994', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Evan', 'Mobley', 'JUN 18, 2001', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Sam', 'Merrill', 'MAY 15, 1996', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Craig', 'Porter Jr.', 'FEB 26, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Darius', 'Garland', 'JAN 26, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Tristan', 'Thompson', 'MAR 13, 1991', 'C-F', NULL FROM DUAL UNION ALL
  SELECT 'Isaiah', 'Mobley', 'SEP 24, 1999', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Georges', 'Niang', 'JUN 17, 1993', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Emoni', 'Bates', 'JAN 28, 2004', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Damian', 'Jones', 'JUN 30, 1995', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Jarrett', 'Allen', 'APR 21, 1998', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Dean', 'Wade', 'NOV 20, 1996', 'F-C', NULL FROM DUAL UNION ALL
  SELECT 'Isaac', 'Okoro', 'JAN 26, 2001', 'F-G', NULL FROM DUAL UNION ALL
  SELECT 'Donovan', 'Mitchell', 'SEP 07, 1996', 'G', NULL FROM DUAL
);


--Detroit Piston
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Jalen', 'Duren', 'NOV 18, 2003', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Cade', 'Cunningham', 'SEP 25, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Monte', 'Morris', 'JUN 27, 1995', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Killian', 'Hayes', 'JUL 27, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Jared', 'Rhoden', 'AUG 27, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Ausar', 'Thompson', 'JAN 30, 2003', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'James', 'Wiseman', 'MAR 31, 2001', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Alec', 'Burks', 'JUL 20, 1991', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Stanley', 'Umude', 'APR 12, 1999', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Malcolm', 'Cazalon', 'AUG 27, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Jaden', 'Ivey', 'FEB 13, 2002', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Kevin', 'Knox II', 'AUG 11, 1999', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Marcus', 'Sasser', 'SEP 21, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Isaiah', 'Stewart', 'MAY 22, 2001', 'F-C', NULL FROM DUAL UNION ALL
  SELECT 'Joe', 'Harris', 'SEP 06, 1991', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Mike', 'Muscala', 'JUL 01, 1991', 'F-C', NULL FROM DUAL UNION ALL
  SELECT 'Bojan', 'Bogdanovic', 'APR 18, 1989', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Danilo', 'Gallinari', 'AUG 08, 1988', 'F', NULL FROM DUAL
);
   


--Pacers    
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Tyrese', 'Haliburton', 'FEB 29, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Bennedict', 'Mathurin', 'JUN 19, 2002', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Obi', 'Toppin', 'MAR 04, 1998', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Andrew', 'Nembhard', 'JAN 16, 2000', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Jarace', 'Walker', 'SEP 04, 2003', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Buddy', 'Hield', 'DEC 17, 1992', 'G', NULL FROM DUAL UNION ALL
  SELECT 'T.J.', 'McConnell', 'MAR 25, 1992', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Kendall', 'Brown', 'MAY 11, 2003', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Bruce', 'Brown', 'AUG 15, 1996', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Jordan', 'Nwora', 'SEP 09, 1998', 'F', NULL FROM DUAL UNION ALL
  SELECT 'James', 'Johnson', 'FEB 20, 1987', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Isaiah', 'Wong', 'JAN 28, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Isaiah', 'Jackson', 'JAN 10, 2002', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Aaron', 'Nesmith', 'OCT 16, 1999', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Jalen', 'Smith', 'MAR 16, 2000', 'F-C', NULL FROM DUAL UNION ALL
  SELECT 'Ben', 'Sheppard', 'JUL 16, 2001', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Myles', 'Turner', 'MAR 24, 1996', 'C-F', NULL FROM DUAL UNION ALL
  SELECT 'Oscar', 'Tshiebwe', 'NOV 27, 1999', 'F-C', NULL FROM DUAL
);


--Atlanta Hawks
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Jalen', 'Johnson', 'DEC 18, 2001', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Trent', 'Forrest', 'JUN 12, 1998', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Seth', 'Lundy', 'APR 02, 2000', 'G-F', NULL FROM DUAL UNION ALL
  SELECT 'Kobe', 'Bufkin', 'SEP 21, 2003', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Dejounte', 'Murray', 'SEP 19, 1996', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Patty', 'Mills', 'AUG 11, 1988', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Trae', 'Young', 'SEP 19, 1998', 'G', NULL FROM DUAL UNION ALL
  SELECT 'De''Andre', 'Hunter', 'DEC 02, 1997', 'F-G', NULL FROM DUAL UNION ALL
  SELECT 'Bogdan', 'Bogdanovic', 'AUG 18, 1992', 'G', NULL FROM DUAL UNION ALL
  SELECT 'AJ', 'Griffin', 'AUG 25, 2003', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Clint', 'Capela', 'MAY 18, 1994', 'C', NULL FROM DUAL UNION ALL
  SELECT 'Onyeka', 'Okongwu', 'DEC 11, 2000', 'F-C', NULL FROM DUAL UNION ALL
  SELECT 'Mouhamed', 'Gueye', 'NOV 09, 2002', 'F', NULL FROM DUAL UNION ALL
  SELECT 'Bruno', 'Fernando', 'AUG 15, 1998', 'F-C', NULL FROM DUAL UNION ALL
  SELECT 'Garrison', 'Mathews', 'OCT 24, 1996', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Vit', 'Krejci', 'JUN 19, 2000', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Wesley', 'Matthews', 'OCT 14, 1986', 'G', NULL FROM DUAL UNION ALL
  SELECT 'Saddiq', 'Bey', 'APR 09, 1999', 'G-F', NULL FROM DUAL
);

--Charlotte Hornets
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Nathan', 'Mensah', 'APR 09, 1998', 'C' FROM DUAL UNION ALL
  SELECT 'Miles', 'Bridges', 'MAR 21, 1998', 'F' FROM DUAL UNION ALL
  SELECT 'LaMelo', 'Ball', 'AUG 22, 2001', 'G' FROM DUAL UNION ALL
  SELECT 'James', 'Bouknight', 'SEP 18, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'Terry', 'Rozier', 'MAR 17, 1994', 'G' FROM DUAL UNION ALL
  SELECT 'Nick', 'Richards', 'NOV 29, 1997', 'C' FROM DUAL UNION ALL
  SELECT 'Mark', 'Williams', 'DEC 16, 2001', 'C' FROM DUAL UNION ALL
  SELECT 'Bryce', 'McGowens', 'NOV 08, 2002', 'G' FROM DUAL UNION ALL
  SELECT 'Nick', 'Smith Jr.', 'APR 18, 2004', 'G' FROM DUAL UNION ALL
  SELECT 'Amari', 'Bailey', 'FEB 17, 2004', 'G' FROM DUAL UNION ALL
  SELECT 'Cody', 'Martin', 'SEP 28, 1995', 'F' FROM DUAL UNION ALL
  SELECT 'Leaky', 'Black', 'JUN 14, 1999', 'F' FROM DUAL UNION ALL
  SELECT 'Ish', 'Smith', 'JUL 05, 1988', 'G' FROM DUAL UNION ALL
  SELECT 'Gordon', 'Hayward', 'MAR 23, 1990', 'F' FROM DUAL UNION ALL
  SELECT 'JT', 'Thor', 'AUG 26, 2002', 'F' FROM DUAL UNION ALL
  SELECT 'Brandon', 'Miller', 'NOV 22, 2002', 'F' FROM DUAL UNION ALL
  SELECT 'P.J.', 'Washington', 'AUG 23, 1998', 'F' FROM DUAL UNION ALL
  SELECT 'Frank', 'Ntilikina', 'JUL 28, 1998', 'G' FROM DUAL
);


    
--Miami Heat

INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Josh', 'Richardson', 'SEP 15, 1993', 'G' FROM DUAL UNION ALL
  SELECT 'R.J.', 'Hampton', 'FEB 07, 2001', 'G' FROM DUAL UNION ALL
  SELECT 'Nikola', 'Jovic', 'JUN 09, 2003', 'F' FROM DUAL UNION ALL
  SELECT 'Kyle', 'Lowry', 'MAR 25, 1986', 'G' FROM DUAL UNION ALL
  SELECT 'Jamal', 'Cain', 'MAR 20, 1999', 'F' FROM DUAL UNION ALL
  SELECT 'Dru', 'Smith', 'DEC 30, 1997', 'G' FROM DUAL UNION ALL
  SELECT 'Jaime', 'Jaquez Jr.', 'FEB 18, 2001', 'G' FROM DUAL UNION ALL
  SELECT 'Bam', 'Adebayo', 'JUL 18, 1997', 'C-F' FROM DUAL UNION ALL
  SELECT 'Tyler', 'Herro', 'JAN 20, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'Caleb', 'Martin', 'SEP 28, 1995', 'F' FROM DUAL UNION ALL
  SELECT 'Cole', 'Swider', 'MAY 08, 1999', 'F' FROM DUAL UNION ALL
  SELECT 'Jimmy', 'Butler', 'SEP 14, 1989', 'F' FROM DUAL UNION ALL
  SELECT 'Haywood', 'Highsmith', 'DEC 09, 1996', 'F' FROM DUAL UNION ALL
  SELECT 'Orlando', 'Robinson', 'JUL 10, 2000', 'C' FROM DUAL UNION ALL
  SELECT 'Thomas', 'Bryant', 'JUL 31, 1997', 'C-F' FROM DUAL UNION ALL
  SELECT 'Kevin', 'Love', 'SEP 07, 1988', 'F-C' FROM DUAL UNION ALL
  SELECT 'Duncan', 'Robinson', 'APR 22, 1994', 'F' FROM DUAL
);

--Orlando Magic
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Anthony', 'Black', 'JAN 20, 2004', 'G' FROM DUAL UNION ALL
  SELECT 'Jonathan', 'Isaac', 'OCT 03, 1997', 'F' FROM DUAL UNION ALL
  SELECT 'Caleb', 'Houstan', 'JAN 09, 2003', 'G' FROM DUAL UNION ALL
  SELECT 'Chuma', 'Okeke', 'AUG 18, 1998', 'F' FROM DUAL UNION ALL
  SELECT 'Jalen', 'Suggs', 'JUN 03, 2001', 'G' FROM DUAL UNION ALL
  SELECT 'Paolo', 'Banchero', 'NOV 12, 2002', 'F' FROM DUAL UNION ALL
  SELECT 'Joe', 'Ingles', 'OCT 02, 1987', 'F-G' FROM DUAL UNION ALL
  SELECT 'Kevon', 'Harris', 'JUN 24, 1997', 'G' FROM DUAL UNION ALL
  SELECT 'Trevelin', 'Queen', 'FEB 25, 1997', 'G' FROM DUAL UNION ALL
  SELECT 'Jett', 'Howard', 'SEP 14, 2003', 'G' FROM DUAL UNION ALL
  SELECT 'Gary', 'Harris', 'SEP 14, 1994', 'G' FROM DUAL UNION ALL
  SELECT 'Markelle', 'Fultz', 'MAY 29, 1998', 'G' FROM DUAL UNION ALL
  SELECT 'Moritz', 'Wagner', 'APR 26, 1997', 'F-C' FROM DUAL UNION ALL
  SELECT 'Franz', 'Wagner', 'AUG 27, 2001', 'F' FROM DUAL UNION ALL
  SELECT 'Admiral', 'Schofield', 'MAR 30, 1997', 'F' FROM DUAL UNION ALL
  SELECT 'Wendell', 'Carter Jr.', 'APR 16, 1999', 'C-F' FROM DUAL UNION ALL
  SELECT 'Goga', 'Bitadze', 'JUL 20, 1999', 'C-F' FROM DUAL UNION ALL
  SELECT 'Cole', 'Anthony', 'MAY 15, 2000', 'G' FROM DUAL
);


--Washington wizzard
INSERT INTO PLAYER (PLAYER_ID, FIRST_NAME, LAST_NAME, BIRTHDATE, POSITION, TEAM_ID)
SELECT
  player_id_seq.NEXTVAL,
  FIRST_NAME,
  LAST_NAME,
  TO_DATE(BIRTHDATE, 'MON DD, YYYY'),
  POSITION,
  NULL
FROM (
  SELECT 'Bilal', 'Coulibaly', 'JUL 26, 2004', 'G' FROM DUAL UNION ALL
  SELECT 'Johnny', 'Davis', 'FEB 27, 2002', 'G' FROM DUAL UNION ALL
  SELECT 'Jared', 'Butler', 'AUG 25, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'Tyus', 'Jones', 'MAY 10, 1996', 'G' FROM DUAL UNION ALL
  SELECT 'Patrick', 'Baldwin Jr.', 'NOV 18, 2002', 'F' FROM DUAL UNION ALL
  SELECT 'Deni', 'Avdija', 'JAN 03, 2001', 'F' FROM DUAL UNION ALL
  SELECT 'Hamidou', 'Diallo', 'JUL 31, 1998', 'G' FROM DUAL UNION ALL
  SELECT 'Isaiah', 'Livers', 'JUL 28, 1998', 'F' FROM DUAL UNION ALL
  SELECT 'Jordan', 'Poole', 'JUN 19, 1999', 'G' FROM DUAL UNION ALL
  SELECT 'Jules', 'Bernard', 'JAN 21, 2000', 'G' FROM DUAL UNION ALL
  SELECT 'Anthony', 'Gill', 'OCT 17, 1992', 'F' FROM DUAL UNION ALL
  SELECT 'Landry', 'Shamet', 'MAR 13, 1997', 'G' FROM DUAL UNION ALL
  SELECT 'Daniel', 'Gafford', 'OCT 01, 1998', 'F-C' FROM DUAL UNION ALL
  SELECT 'Corey', 'Kispert', 'MAR 03, 1999', 'F' FROM DUAL UNION ALL
  SELECT 'Kyle', 'Kuzma', 'JUL 24, 1995', 'F' FROM DUAL UNION ALL
  SELECT 'Marvin', 'Bagley III', 'MAR 14, 1999', 'F' FROM DUAL UNION ALL
  SELECT 'Delon', 'Wright', 'APR 26, 1992', 'G' FROM DUAL UNION ALL
  SELECT 'Eugene', 'Omoruyi', 'FEB 14, 1997', 'F' FROM DUAL
);
