--SPONSORZY
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (1,
    'MOTOROLA',
    NULL,
    150000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (2,
    'DISNEY',
    NULL,
    360000);   
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (3,
    'PAYPAL',
    NULL,
    230000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (4,
    'TESLA',
    NULL,
    400000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (5,
    'COCA COLA',
    NULL,
    500000);    
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (6,
    'RAKUTEN',
    NULL,
    450000);   
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (7,
    'MOTOROLA',
    NULL,
    100000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (8,
    'CHIME',
    NULL,
    130000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (9,
    'FEASTABLES',
    NULL,
    160000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (10,
    'WEBULL',
    NULL,
    50000);   
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (11,
    'VISTAPRINT',
    NULL,
    250000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (12,
    'NIKE',
    NULL,
    200000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (13,
    'ADDIDAS',
    NULL,
    265000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (14,
    'PUMA',
    NULL,
    300000);
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (15,
    'GOOGLE',
    NULL,
    420000);

