-- SPONSORZY
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (1, 'MOTOROLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Atlanta Hawks'), 150000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (2, 'DISNEY', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Orlando Magic'), 360000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (3, 'PAYPAL', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Phoenix Suns'), 230000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (4, 'TESLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Golden State Warriors'), 400000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (5, 'COCA COLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Miami Heat'), 500000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (6, 'RAKUTEN', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Golden State Warriors'), 450000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (7, 'MOTOROLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Chicago Bulls'), 100000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (8, 'CHIME', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Dallas Mavericks'), 130000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (9, 'FEASTABLES', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Charlotte Hornets'), 160000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (10, 'WEBULL', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Brooklyn Nets'), 50000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (11, 'VISTAPRINT', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Boston Celtics'), 250000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (12, 'NIKE', NULL, 200000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (13, 'ADDIDAS', NULL, 265000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (14, 'PUMA', NULL, 300000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (15, 'GOOGLE', NULL, 420000);
