CREATE SEQUENCE sponsor_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;

-- SPONSORZY
INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'MOTOROLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Atlanta Hawks'), 150000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'DISNEY', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Orlando Magic'), 360000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'PAYPAL', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Phoenix Suns'), 230000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'TESLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Golden State Warriors'), 400000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'COCA COLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Miami Heat'), 500000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'RAKUTEN', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Golden State Warriors'), 450000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'MOTOROLA', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Chicago Bulls'), 100000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'CHIME', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Dallas Mavericks'), 130000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'FEASTABLES', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Charlotte Hornets'), 160000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'WEBULL', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Brooklyn Nets'), 50000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'VISTAPRINT', (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = 'Boston Celtics'), 250000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'NIKE', NULL, 200000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'ADDIDAS', NULL, 265000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'PUMA', NULL, 300000);

INSERT INTO SPONSOR(SPONSOR_ID, SPONSOR_NAME, TEAM_ID, SPONSORSHIP_AMOUNT) 
VALUES (sponsor_id_seq.NEXTVAL, 'GOOGLE', NULL, 420000);
