INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (1,
    'TD Garden',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'BOSTON CELTICS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (2,
    'Fiserv Forum',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'MILWAUKEE BUCKS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (3,
    'Wells Fargo Center',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'PHILADELPHIA 76ERS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (4,
    'Rocket Mortgage FieldHouse',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'CLEVELAND CAVALIERS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (5,
    'TD Kaseya Center',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'MIAMI HEAT')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (6,
    'Bankers Life Fieldhouse',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'NEW YORK KNICKS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (7,
    'Madison Square Garden',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'INDIANA PACERS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (8,
    'Amway Center',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'ORLANDO MAGIC')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (9,
    'United Center',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'CHICAGO BULLS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (10,
    'Barclays Center',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'BROOKLYN NETS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (11,
    'State Farm Arena',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'ATLANTA HAWKS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (12,
    'Scotiabank Arena',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'TORONTO RAPTORS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (13,
    'Spectrum Center',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'CHARLOTTE HORNETS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (14,
    'Capital One Arena',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'WASHINGTON WIZARDS')
    );
INSERT INTO SPORTOBJECT(OBJECT_ID, OBJECT_NAME, OWNER_TEAM_ID)
VALUES (15,
    'Little Caesars Arena',
    (SELECT REF(t) FROM Team t WHERE t.NAME = 'DETROIT PISTONS')
    );