--Sample example
--INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCETANGE, PLAYERS, SPONSORS)
----VALUES(26, 'DALLAS MAVERICKS', PlayerListType(), SponsorListType());
CREATE SEQUENCE team_id_seq
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE;
  
--re use ids
ALTER SEQUENCE team_id_seq INCREMENT BY -1;
SELECT team_id_seq.NEXTVAL FROM dual;
ALTER SEQUENCE team_id_seq INCREMENT BY 1;

-- Eastern Conference
-- Atlantic Division
-- Boston Celtics
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'BOSTON CELTICS', 32, 9,NULL,NULL,NULL);

-- Brooklyn Nets
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, win_percentage, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'BROOKLYN NETS', 16, 24,NULL,NULL,NULL);

-- New York Knicks
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'NEW YORK KNICKS', 24, 17,NULL,NULL,NULL);

-- Philadelphia 76ers
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'PHILADELPHIA 76ERS', NULL, NULL,NULL,NULL,NULL);

-- Toronto Raptors
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'TORONTO RAPTORS', NULL, NULL,NULL,NULL,NULL);

-- Central Division
-- Chicago Bulls
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'CHICAGO BULLS', NULL, NULL,NULL,NULL,NULL);

-- Cleveland Cavaliers
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'CLEVELAND CAVALIERS', NULL, NULL,NULL,NULL,NULL);

-- Detroit Pistons
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'DETROIT PISTONS', NULL, NULL,NULL,NULL,NULL);

-- Indiana Pacers
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'INDIANA PACERS', NULL, NULL,NULL,NULL,NULL);

-- Milwaukee Bucks
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'MILWAUKEE BUCKS', NULL, NULL,NULL,NULL,NULL);

-- Southeast Division
-- Atlanta Hawks
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'ATLANTA HAWKS', NULL, NULL,NULL,NULL,NULL);

-- Charlotte Hornets
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'CHARLOTTE HORNETS', NULL, NULL,NULL,NULL,NULL);

-- Miami Heat
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'MIAMI HEAT', NULL, NULL,NULL,NULL,NULL);

-- Orlando Magic
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'ORLANDO MAGIC', NULL, NULL,NULL,NULL,NULL);

-- Washington Wizards
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'WASHINGTON WIZARDS', NULL, NULL,NULL,NULL,NULL);

-- Western Conference
-- Northwest Division
-- Denver Nuggets
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'DENVER NUGGETS', NULL, NULL,NULL,NULL,NULL);

-- Minnesota Timberwolves
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'MINNESOTA TIMBERWOLVES', NULL, NULL,NULL,NULL,NULL);

-- Oklahoma City Thunder
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'OKLAHOMA CITY THUNDER', NULL, NULL,NULL,NULL,NULL);

-- Portland Trail Blazers
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'PORTLAND TRAIL BLAZERS', NULL, NULL,NULL,NULL,NULL);

-- Utah Jazz
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'UTAH JAZZ', NULL, NULL,NULL,NULL,NULL);

-- Pacific Division
-- Golden State Warriors
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'GOLDEN STATE WARRIORS', NULL, NULL,NULL,NULL,NULL);

-- LA Clippers
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'LA CLIPPERS', NULL, NULL,NULL,NULL,NULL);

-- Los Angeles Lakers
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'LOS ANGELES LAKERS', NULL, NULL,NULL,NULL,NULL);

-- Phoenix Suns
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'PHOENIX SUNS', NULL, NULL,NULL,NULL,NULL);

-- Sacramento Kings
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'SACRAMENTO KINGS', NULL, NULL,NULL,NULL,NULL);

-- Southwest Division
-- Dallas Mavericks
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'DALLAS MAVERICKS', NULL, NULL,NULL,NULL,NULL);

-- Houston Rockets
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'HOUSTON ROCKETS', NULL, NULL,NULL,NULL,NULL);

-- Memphis Grizzlies
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'MEMPHIS GRIZZLIES', NULL, NULL,NULL,NULL,NULL);

-- New Orleans Pelicans
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'NEW ORLEANS PELICANS', NULL, NULL,NULL,NULL,NULL);

-- San Antonio Spurs
INSERT INTO TEAM(TEAM_ID, NAME, WINS, LOSES, WIN_PERCENTAGE, PLAYERS, SPONSORS)
VALUES(team_id_seq.NEXTVAL, 'SAN ANTONIO SPURS', NULL, NULL,NULL,NULL,NULL);

--DELETE EVERYTHING
DELETE FROM TEAM